version: "3.7"
# to get in interactive shell to generate components
# docker run, runs a command in a new container
# docker run -it -v $(pwd):/app node:16-alpine bash
#
# to run commands in a running container
# docker exec -it <container_id> sh
# or
# docker-compose exec app sh

services:
  app:
    #stdin_open: true # docker run -i
    #tty: true        # docker run -t
    image: node:lts
    command: sh -c "npm install && npm start"
    ports:
      - 4200:4200
    working_dir: /app
    volumes:
      - ./:/app

  storybook:
    image: node:lts
    command: sh -c "npm install && npm run storybook"
    ports:
      - 6006:6006
    working_dir: /app
    volumes:
      - ./:/app
